resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/MJunaidK/concourse-ci-hello-world.git
- name: staging_deployment
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: user 
    password: pass 
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true
    
jobs:
- name: simple_deploy_cf
  plan:
  - get: app_sources
  - put: staging_deployment
    params:
     manifest: app_sources/manifest.yml